#pragma once

#define TOGGLEDISPLAY_VER_MAJOR	1
#define TOGGLEDISPLAY_VER_MINOR	1
#define TOGGLEDISPLAY_VER_PATCH	2
#define TOGGLEDISPLAY_VER_BUILD	0

#define TOGGLEDISPLAY_VER_YEARSTR	"2023-2024"
