bell: true     # accustic feedback when hotkey is triggered

globalhotkeys: # all hotkeys are configured in this list

- code: Ä      # character check for system encoding; change on non-DE systems
  shift: true
  alt: true
  ctrl: true
  exec: "pwsh.exe"
  workdir: "C:\\"
  args:
  - -NoExit
  - "-c"
  - "Write-Host \"Hello World.\""
  createnowindow: false  # by default a window of the command line triggered by the hotkey is suppressed
                         # With this setting, the window will be shown

- code: n
  shift: true
  alt: true
  ctrl: true
  exec: "notepad.exe"
