//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileBookmark {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileBookmark.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark File.
        /// </summary>
        internal static string CommandBookmark {
            get {
                return ResourceManager.GetString("CommandBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark and Open File.
        /// </summary>
        internal static string CommandBookmarkAndOpen {
            get {
                return ResourceManager.GetString("CommandBookmarkAndOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string CommandOpenFile {
            get {
                return ResourceManager.GetString("CommandOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Bookmark.
        /// </summary>
        internal static string CommandUnBookmark {
            get {
                return ResourceManager.GetString("CommandUnBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Bookmark.
        /// </summary>
        internal static string FileTypeName {
            get {
                return ResourceManager.GetString("FileTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Bookmarks cannot be set, removed or opened when the application is un-/registering. File options will be ignored..
        /// </summary>
        internal static string IgnoreFilesOnRegWarning {
            get {
                return ResourceManager.GetString("IgnoreFilesOnRegWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of application {0}..
        /// </summary>
        internal static string RegistrationResult {
            get {
                return ResourceManager.GetString("RegistrationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register and unregister application at the same time..
        /// </summary>
        internal static string RegUnregError {
            get {
                return ResourceManager.GetString("RegUnregError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        internal static string ResultFailed {
            get {
                return ResourceManager.GetString("ResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful.
        /// </summary>
        internal static string ResultSuccess {
            get {
                return ResourceManager.GetString("ResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is not to be called directly. Do you want to (re-)register the application for use from the Explorer context menu?.
        /// </summary>
        internal static string StartRegistryQuestion {
            get {
                return ResourceManager.GetString("StartRegistryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistration of application {0}..
        /// </summary>
        internal static string UnregistrationResult {
            get {
                return ResourceManager.GetString("UnregistrationResult", resourceCulture);
            }
        }
    }
}
